title: TrueAsync
description: True Asynchronous inside PHP
url: https://true-async.github.io
baseurl: ""
repository: true-async/true-async.github.io

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: null

permalink: pretty

exclude:
  - README.md
  - .idea
  - .claude
  - plantuml.jar

defaults:
  - scope:
      path: ""
    values:
      layout: default
